"""
Seeds the database with:
  - the versioned compliance rule set (data/compliance_rules.json)
  - two demo Inspector accounts and one Admin account
  - three switchable demo inspections (compliant / non-compliant / needs
    review), generated by actually running the real extraction and rule
    engine modules over fixed sample label text — see demo_asset_generator.py
    and the _DEMO_SCENARIOS table below for exactly what each contains.

Run with:  python -m app.seed
"""
from __future__ import annotations

import datetime as dt
import json
import os
import shutil

from app.config import DEMO_ASSETS_DIR, RULES_FILE, UPLOAD_DIR
from app.database import Base, SessionLocal, engine
from app.demo_asset_generator import ensure_demo_assets
from app.extraction import extract_fields
from app.models import ComplianceRule, ImageAsset, Inspection, User
from app.rules_engine import evaluate_rules, overall_result_from
from app.security import hash_password

_DEMO_SCENARIOS = [
    {
        "key": "compliant",
        "code_suffix": "0001",
        "product_category": "Edible Oil",
        "product_name": "Sunflower Cooking Oil",
        "brand": "GreenValley Kitchen",
        "ocr_text": (
            "GREENVALLEY KITCHEN\nRefined Sunflower Cooking Oil\n"
            "Mfg. Date: 03/2026\nNet Wt. 1 L\nMRP Rs. 185.00 incl. of all taxes\n"
            "Manufactured and Packed by: GreenValley AgroFoods Pvt. Ltd., Plot 14, "
            "MIDC Industrial Area, Nashik, Maharashtra - 422010\n"
            "Consumer Care: care@greenvalleykitchen.in Toll Free 1800-419-2233\n"
            "FSSAI Lic. No. 10419022001234\nBest Before 12 months from Mfg. Date\nVegetarian"
        ),
        "image_quality": {
            "resolution": {"status": "GOOD", "detail": "1200x900px captured — well above the recommended minimum."},
            "clarity": {"status": "GOOD", "detail": "Sharp focus across the principal display panel."},
            "lighting": {"status": "GOOD", "detail": "Even, well-lit capture."},
            "label_visibility": {"status": "GOOD", "detail": "Label fully visible with strong contrast."},
            "text_readability": {"status": "GOOD", "detail": "All declarations legible at full resolution."},
        },
    },
    {
        "key": "non_compliant",
        "code_suffix": "0002",
        "product_category": "Biscuits & Snacks",
        "product_name": "Wheat Crackers Biscuits",
        "brand": "FreshBite",
        "ocr_text": (
            "FRESHBITE\nWheat Crackers Biscuits\nMfg Date: 06/2026\nNet Wt. 100 g\n"
            "MRP Rs. 30.00 incl. of all taxes\n"
            "For Customer Care queries, please contact us."
        ),
        "image_quality": {
            "resolution": {"status": "GOOD", "detail": "1000x800px."},
            "clarity": {"status": "REVIEW", "detail": "Sharpness below threshold — image appears slightly blurred."},
            "lighting": {"status": "GOOD", "detail": "Adequate lighting."},
            "label_visibility": {"status": "REVIEW", "detail": "Lower panel has reduced contrast against background."},
            "text_readability": {"status": "REVIEW", "detail": "OCR word confidence low on the lower label panel."},
        },
    },
    {
        "key": "needs_review",
        "code_suffix": "0003",
        "product_category": "Health Food",
        "product_name": "Whey Protein Bar",
        "brand": "Nutrimax",
        "ocr_text": (
            "NUTRIMAX\nWhey Protein Bar - Chocolate Flavour\nPkd on 07/2026\n35g\n"
            "MRP Rs. 60.00\nManufactured by: Nutrimax Wellness Foods, Sector 8, Gurugram, Haryana\n"
            "customercare@nutrimaxfoods.com"
        ),
        "image_quality": {
            "resolution": {"status": "GOOD", "detail": "1100x850px."},
            "clarity": {"status": "GOOD", "detail": "Sharp capture."},
            "lighting": {"status": "GOOD", "detail": "Even lighting."},
            "label_visibility": {"status": "GOOD", "detail": "Label clearly visible."},
            "text_readability": {"status": "GOOD", "detail": "Text legible; net quantity printed in a smaller, low-contrast font."},
        },
    },
]


def _load_active_rules(db):
    return [
        {
            "rule_id": r.rule_id, "name": r.name, "legal_reference": r.legal_reference,
            "field_key": r.field_key, "check_type": r.check_type,
            "applicability": r.applicability, "active": r.active,
        }
        for r in db.query(ComplianceRule).filter(ComplianceRule.active == True).all()  # noqa: E712
    ]


def seed_rules(db):
    if db.query(ComplianceRule).count() > 0:
        return
    with open(RULES_FILE) as f:
        rules = json.load(f)
    for r in rules:
        db.add(ComplianceRule(**r))
    db.commit()


def seed_users(db):
    if db.query(User).count() > 0:
        return
    users = [
        User(name="Ananya Sharma", email="inspector@nirakshan.gov.in",
             password_hash=hash_password("Inspector@123"), role="inspector",
             designation="Legal Metrology Inspector"),
        User(name="Rohan Verma", email="inspector2@nirakshan.gov.in",
             password_hash=hash_password("Inspector@123"), role="inspector",
             designation="Legal Metrology Inspector"),
        User(name="Priya Nair", email="admin@nirakshan.gov.in",
             password_hash=hash_password("Admin@123"), role="admin",
             designation="Controller of Legal Metrology"),
    ]
    db.add_all(users)
    db.commit()


def seed_demo_inspections(db):
    if db.query(Inspection).filter(Inspection.is_demo == True).count() > 0:  # noqa: E712
        return

    demo_paths = ensure_demo_assets(DEMO_ASSETS_DIR)
    inspector = db.query(User).filter(User.role == "inspector").first()
    active_rules = _load_active_rules(db)

    demo_upload_dir = os.path.join(UPLOAD_DIR, "demo")
    os.makedirs(demo_upload_dir, exist_ok=True)

    for i, scenario in enumerate(_DEMO_SCENARIOS):
        extracted = extract_fields(
            scenario["ocr_text"], ocr_mode="demo", ocr_avg_confidence=0,
            product_name=scenario["product_name"], category=scenario["product_category"],
        )
        rule_results = evaluate_rules(extracted, scenario["image_quality"], is_imported=False, rules=active_rules)
        overall, issues = overall_result_from(rule_results)

        inspection = Inspection(
            inspection_code=f"NIR-2026-DEMO-{scenario['code_suffix']}",
            product_category=scenario["product_category"],
            product_name=scenario["product_name"],
            brand=scenario["brand"],
            other_details="Prototype Sample Data — generated for demonstration purposes.",
            is_imported=False,
            inspector_id=inspector.id if inspector else None,
            status="completed",
            overall_result=overall,
            issues_count=issues,
            image_quality_json=json.dumps(scenario["image_quality"]),
            ocr_text=scenario["ocr_text"],
            ocr_mode="demo",
            extracted_data_json=json.dumps(extracted),
            rule_results_json=json.dumps(rule_results),
            is_demo=True,
            created_at=dt.datetime.utcnow() - dt.timedelta(days=3 - i),
            completed_at=dt.datetime.utcnow() - dt.timedelta(days=3 - i),
        )
        db.add(inspection)
        db.flush()

        src = demo_paths[scenario["key"]]
        dest_name = f"{inspection.id}_front.png"
        dest_path = os.path.join(demo_upload_dir, dest_name)
        shutil.copyfile(src, dest_path)
        db.add(ImageAsset(
            inspection_id=inspection.id, image_type="front",
            file_path=f"demo/{dest_name}", original_filename=dest_name,
        ))

    db.commit()


def run():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        seed_rules(db)
        seed_users(db)
        seed_demo_inspections(db)
        print("Seed complete: rules, users and demo inspections are ready.")
        print("Inspector login:  inspector@nirakshan.gov.in / Inspector@123")
        print("Admin login:      admin@nirakshan.gov.in / Admin@123")
    finally:
        db.close()


if __name__ == "__main__":
    run()
